# This file is automatically generated. Do not edit.

if Object.const_defined?('TestFlight') and !UIDevice.currentDevice.model.include?('Simulator')
  NSNotificationCenter.defaultCenter.addObserverForName(UIApplicationDidBecomeActiveNotification, object:nil, queue:nil, usingBlock:lambda do |notification|
  
  TestFlight.takeOff('7b3f8f31240990f5d5b916404935a877_MjE0MzQ4MjAxMy0wNC0yMSAxMTo0NjozOC44MzcwMTA')
  end)
end
