# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project'
require 'rubygems'
require 'bundler'
Bundler.require(:RubyMotion)

# GCAM
# Ruby Camera FX App
# Fix Rotation

Motion::Project::App.setup do |app|
  app.name = 'GCam'

  app.device_family = [:iphone]

  app.interface_orientations = [:portrait]

  app.deployment_target = '5.1'

  app.vendor_project('vendor/Filtrr/FiltrrApp/FiltrrApp/Filtrr', :static)

  app.vendor_project('vendor/GPUImage/framework', :xcode,
  :target => 'GPUImage',
  :headers_dir => 'Source')

  app.frameworks << 'OpenGLES'
  app.frameworks << 'QuartzCore'
  app.frameworks << 'CoreVideo'
  app.frameworks << 'CoreMedia'
  app.frameworks << 'AVFoundation'
end
