# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project'
require 'rubygems'
require 'bundler'
Bundler.require(:RubyMotion)

# GCAM
# Ruby Camera FX App
# Fix Rotation

Motion::Project::App.setup do |app|

  app.identifier = 'com.jonsoft.gcam'
  app.info_plist['CFBundleShortVersionString'] = "1.1.1"
  app.short_version = "1.1"
  app.version       = "1.1"

  app.provisioning_profile = "/Users/jsilverman2/Library/MobileDevice/Provisioning Profiles/60F7EEB6-6E11-4713-9039-839CDBB930D4.mobileprovision"
  app.codesign_certificate = "iPhone Distribution: Jonathan Silverman"

  app.info_plist['UILaunchImageFile'] = 'launch'

  app.icons = ['icon_iphone.png', 'icon_ipad.png', 'icon_iphone_retina.png', 'icon_ipad_retina.png']
  app.prerendered_icon = true

  app.name = 'Global Camera'

  app.device_family = [:iphone]

  app.interface_orientations = [:portrait]

  app.deployment_target = '6.1'

  app.vendor_project('vendor/Filtrr/FiltrrApp/FiltrrApp/Filtrr', :static)

  # app.vendor_project('vendor/GPUImage/framework', :xcode,
  # :target => 'GPUImage',
  # :headers_dir => 'Source')

  app.frameworks << 'OpenGLES'
  app.frameworks << 'QuartzCore'
  app.frameworks << 'CoreVideo'
  app.frameworks << 'CoreMedia'
  app.frameworks << 'AVFoundation'
  app.frameworks << 'AdSupport'
  app.frameworks << 'Accounts'
  app.frameworks << 'Social'

  {
    'DTSDKName'         => 'iphoneos6.0',
    'DTPlatformVersion' => '6.0',
    'DTXcode'           => '0450',
    'DTSDKBuild'        => '10A403',
    'DTXcodeBuild'      => '4G182',
    'DTPlatformBuild'   => '10A403'
  }.each do |k, v|
    app.info_plist[k] = v
  end

  app.pods do
    pod 'ShareKit/Facebook'
    pod 'ShareKit/Twitter'
  end

  app.testflight.sdk = 'vendor/TestFlight'
  app.testflight.api_token = '9f04bee16d21fa6dc5752e65cca07035_MTAwMjgxODIwMTMtMDQtMjAgMTM6MjY6NDIuNTg3NDQy'
  app.testflight.team_token = '7b3f8f31240990f5d5b916404935a877_MjE0MzQ4MjAxMy0wNC0yMSAxMTo0NjozOC44MzcwMTA'

end
