// Generated by IB v0.2.4 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>
#import <UIKit/UIKit.h>

@interface ParserError : StandardError







@end


@interface InvalidURLError : StandardError







@end


@interface InvalidPlayerType : StandardError







@end


@interface NilPlayerCallback : StandardError





-(IBAction) stop;
-(IBAction) media_player;
-(IBAction) set_player_options:(id) options;

@end


@interface SugarNotFoundException : Exception







@end


@interface BackPanelController : UIViewController







@end



