// Generated by IB v0.2.4 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>
#import <UIKit/UIKit.h>

@interface ParserError : StandardError







@end


@interface InvalidURLError : StandardError







@end


@interface InvalidPlayerType : StandardError







@end


@interface NilPlayerCallback : StandardError





-(IBAction) stop;
-(IBAction) media_player;
-(IBAction) set_player_options:(id) options;

@end


@interface SugarNotFoundException : Exception







@end


@interface PanelController : UIViewController

@property IBOutlet id image_view;
@property IBOutlet id output_image_view;
@property IBOutlet id table_view;



-(IBAction) frontCamera:(id) sender;
-(IBAction) backCamera:(id) sender;
-(IBAction) preferredInterfaceOrientationForPresentation;
-(IBAction) supportedInterfaceOrientations;
-(IBAction) shouldAutorotate;
-(IBAction) shouldAutorotateToInterfaceOrientation:(id) interface;
-(IBAction) viewWillAppear:(id) animated;
-(IBAction) saveImage:(id) sender;
-(IBAction) toLibrary:(id) sender;

@end



