// Generated by IB v0.2.5 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import "Stubs.h"

@implementation ParserError

@end


@implementation InvalidURLError

@end


@implementation InvalidPlayerType

@end


@implementation NilPlayerCallback

@end


@implementation SugarNotFoundException

@end


@implementation PanelController

@end



